export function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
export function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y);const m=b.length>>1;return b.length%2?b[m]:(b[m-1]+b[m])/2}
export function mean(a){return a.length?a.reduce((s,v)=>s+v,0)/a.length:0}
export function smooth(a,r=3){if(r<=0)return a.slice();const out=new Array(a.length);let sum=0;const q=[];for(let i=0;i<a.length;i++){q.push(a[i]);sum+=a[i];if(q.length>2*r+1)sum-=q.shift();out[i]=sum/q.length}return out}
export function rgbDist(a,b){return Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2])}
export function grayAt(data,i){return .299*data[i]+.587*data[i+1]+.114*data[i+2]}
export function getRGB(data,w,x,y){const i=(y*w+x)*4;return [data[i],data[i+1],data[i+2]]}
export function cropCanvas(src,x,y,w,h){x=Math.floor(x);y=Math.floor(y);w=Math.max(1,Math.floor(w));h=Math.max(1,Math.floor(h));const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(src,x,y,w,h,0,0,w,h);return c}
export function canvasData(canvas){return canvas.getContext("2d",{willReadFrequently:true}).getImageData(0,0,canvas.width,canvas.height)}
export function toGrayCanvas(canvas){const d=canvasData(canvas),o=new ImageData(d.width,d.height),g=o.data;for(let i=0;i<d.data.length;i+=4){const v=grayAt(d.data,i);g[i]=g[i+1]=g[i+2]=v;g[i+3]=255}const c=document.createElement("canvas");c.width=d.width;c.height=d.height;c.getContext("2d").putImageData(o,0,0);return c}
function otsuThreshold(gray){const hist=new Uint32Array(256);for(let i=0;i<gray.length;i+=4)hist[Math.round(gray[i])]++;let total=gray.length/4,sum=0;for(let t=0;t<256;t++)sum+=t*hist[t];let sumB=0,wB=0,max=-1,thr=127;for(let t=0;t<256;t++){wB+=hist[t];if(!wB)continue;const wF=total-wB;if(!wF)break;sumB+=t*hist[t];const mB=sumB/wB,mF=(sum-sumB)/wF;const between=wB*wF*(mB-mF)**2;if(between>max){max=between;thr=t}}return thr}
export function thresholdCanvas(canvas,mode="otsu",invert=false){const d=canvasData(canvas),a=d.data;const g=new Uint8ClampedArray(a.length);let t=127;if(mode==="otsu")t=otsuThreshold(a);else if(typeof mode==="number")t=mode;const w=d.width,h=d.height;for(let y=0;y<h;y++)for(let x=0;x<w;x++){let sum=0,n=0;for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){const xx=clamp(x+dx,0,w-1),yy=clamp(y+dy,0,h-1);sum+=grayAt(a,(yy*w+xx)*4);n++}let v=sum/n;let on=mode==="adaptive"?v>(sum/25)+10:v>t; if(invert)on=!on;const i=(y*w+x)*4;g[i]=g[i+1]=g[i+2]=on?255:0;g[i+3]=255}const out=new ImageData(g,w,h),c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").putImageData(out,0,0);return c}
export function preprocess(canvas,{invert=false,mode="otsu",scale=2}={}){const gray=toGrayCanvas(canvas);let p=thresholdCanvas(gray,mode,invert);if(scale!==1){const c=document.createElement("canvas");c.width=gray.width*scale;c.height=gray.height*scale;c.getContext("2d").imageSmoothingEnabled=false;c.getContext("2d").drawImage(p,0,0,c.width,c.height);p=c}return p}
