import {cropCanvas} from './image.js';

export function qs(id){return document.getElementById(id)}
export function setStatus(text,kind=''){const el=qs('status');el.textContent=text;el.className='status '+kind}
export function toast(msg){const el=qs('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
export function drawSource(img,canvas){canvas.width=img.naturalWidth||img.width;canvas.height=img.naturalHeight||img.height;canvas.getContext('2d').drawImage(img,0,0);const out=qs('sourceImage');out.src=canvas.toDataURL('image/jpeg',.88);out.hidden=false;qs('emptyState').hidden=true}

export function renderResults(r){for(const [id,key] of [['resultTitle','title'],['resultDifficulty','difficulty'],['resultLevel','level'],['resultPerfect','perfect'],['resultGreat','great'],['resultGood','good'],['resultBad','bad'],['resultMiss','miss'],['resultCombo','combo']])qs(id).textContent=r[key]??'—'}
export function renderCoords(layout){const el=qs('coords');const items=[['白枠',`L=${layout.frame.left} R=${layout.frame.right} B=${layout.frame.bottom}`],['ジャケット',`L=${layout.jacket.left} R=${layout.jacket.right} T=${layout.jacket.top} B=${layout.jacket.bottom}`],['ゲージ',`L=${layout.gauge.left}`],['難易度',`L=${layout.difficulty.left} R=${layout.difficulty.right}`],['レベル',`L=${layout.level.left} R=${layout.level.right}`],['PERFECT',`T=${layout.rows.perfect.top} B=${layout.rows.perfect.bottom}`],['GOOD',`T=${layout.rows.good.top} B=${layout.rows.good.bottom}`],['MISS',`T=${layout.rows.miss.top} B=${layout.rows.miss.bottom}`],['スコア列',`L=${layout.score.left} R=${layout.score.right}`],['LATE/FAST',`L=${layout.lateFast.left}`]];el.innerHTML=items.map(([a,b])=>`<div><b>${a}</b> ${b}</div>`).join('')}
export function renderRegions(srcCanvas,regions,ocrResults){const root=qs('regionGrid');root.innerHTML='';for(const k of 'ABCDEFGHI'.split('')){const r=regions[k];const pre=cropCanvas(srcCanvas,r.x1,r.y1,r.x2-r.x1,r.y2-r.y1);const result=ocrResults[k];const card=document.createElement('article');card.className='region-card';const name={A:'楽曲タイトル',B:'楽曲難易度',C:'楽曲レベル',D:'PERFECT',E:'GREAT',F:'GOOD',G:'BAD',H:'MISS',I:'COMBO'}[k];const before=document.createElement('img');before.src=pre.toDataURL();const after=document.createElement('img');after.src=result?.processedCanvas?.toDataURL()||before.src;card.innerHTML=`<header><span>${k}：${name}</span><span class="label">${result?.confidence!=null?Math.round(result.confidence)+'%':''}</span></header>`;const imgs=document.createElement('div');imgs.className='region-images';const f1=document.createElement('figure'),f2=document.createElement('figure');f1.append(before,caption('処理前'));f2.append(after,caption('2値化後'));imgs.append(f1,f2);card.append(imgs);const foot=document.createElement('footer');foot.textContent=result?`OCR: ${result.raw||'（空）'} → ${result.cleaned||'（認識できず）'}`:'—';card.append(foot);root.append(card)}}
function caption(t){const c=document.createElement('figcaption');c.textContent=t;return c}

export function renderScans(scans){const root=qs('scanProfiles');root.innerHTML='';for(const s of scans){const box=document.createElement('div');box.className='scan-profile';box.innerHTML=`<h3>${s.name}</h3>`;const c=document.createElement('canvas');c.width=900;c.height=260;box.append(c);drawProfile(c,s.profile);root.append(box)}}
function drawProfile(c,p){const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#5d77ff';ctx.lineWidth=2;ctx.beginPath();let max=Math.max(1,...p);for(let i=0;i<p.length;i++){const x=i/(p.length-1)*c.width,y=c.height-14-(p[i]/max)*(c.height-28);if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke()}

export function downloadText(filename,text,type='application/json'){const a=document.createElement('a');const href=URL.createObjectURL(new Blob([text],{type}));a.href=href;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000)}
export function downloadBlob(filename,blob){const a=document.createElement('a');const href=URL.createObjectURL(blob);a.href=href;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),1000)}
